apiVersion: apps/v1
kind: Deployment
metadata:
  name: pass-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pass-db
  template:
    metadata:
      labels:
        app: pass-db
        tags.datadoghq.com/env: "dev"
        tags.datadoghq.com/service: "pass-db"        
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
