apiVersion: v1
kind: Service
metadata:
  name: pass-db
  labels:
    tags.datadoghq.com/env: "dev"
    tags.datadoghq.com/service: "pass-db"
spec:
  selector:
    app: pass-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
