resources:
  - ../../base

configMapGenerator:
  - name: simple-api-config
    behavior: merge
    literals:
      - DD_ENVIRONMENT=dev
      - DD_VERSION=b1c7655

  - name: downstream-api-config
    behavior: merge
    literals:
      - DD_ENVIRONMENT=dev
      - DD_VERSION=b1c7655

images:
  - name: ghcr.io/scottgerring/simple-api
    newTag: "b1c7655"

  - name: ghcr.io/scottgerring/downstream-api
    newTag: "b1c7655"
