resources:
  - ../../base

configMapGenerator:
  - name: pass-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=d225bdebc3690e58e2a23d47917eb53f0e02dbde

  - name: pass-summary-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=d225bdebc3690e58e2a23d47917eb53f0e02dbde

  - name: pass-image-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=d225bdebc3690e58e2a23d47917eb53f0e02dbde

  - name: load-test-service-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=d225bdebc3690e58e2a23d47917eb53f0e02dbde

images:
  - name: ghcr.io/datadog/sdlc-gitops-sample-stack/pass-api
    newTag: "d225bdebc3690e58e2a23d47917eb53f0e02dbde"

  - name: ghcr.io/datadog/sdlc-gitops-sample-stack/pass-summary-api
    newTag: "d225bdebc3690e58e2a23d47917eb53f0e02dbde"

  - name: ghcr.io/datadog/sdlc-gitops-sample-stack/pass-image-api
    newTag: "d225bdebc3690e58e2a23d47917eb53f0e02dbde"

  - name: ghcr.io/datadog/sdlc-gitops-sample-stack/load-test-service
    newTag: "d225bdebc3690e58e2a23d47917eb53f0e02dbde"
