resources:
  - ../../base

configMapGenerator:
  - name: pass-api-config
    behavior: merge
    literals:
      - DD_ENVIRONMENT=dev
      - DD_VERSION=e4f0733

  - name: pass-summary-api-config
    behavior: merge
    literals:
      - DD_ENVIRONMENT=dev
      - DD_VERSION=e4f0733

images:
  - name: ghcr.io/DataDog/sdlc-gitops-sample-stack/pass-api
    newTag: "e4f0733"

  - name: ghcr.io/DataDog/sdlc-gitops-sample-stack/pass-summary-api
    newTag: "e4f0733"
