resources:
  - ../../base

configMapGenerator:
  - name: pass-api-config
    behavior: merge
    literals:
      - DD_ENVIRONMENT=dev
      - DD_VERSION=7f92e4a

  - name: pass-summary-api-config
    behavior: merge
    literals:
      - DD_ENVIRONMENT=dev
      - DD_VERSION=7f92e4a

images:
  - name: ghcr.io/datadog/sdlc-gitops-sample-stack/pass-api
    newTag: "7f92e4a"

  - name: ghcr.io/datadog/sdlc-gitops-sample-stack/pass-summary-api
    newTag: "7f92e4a"
