resources:
  - ../../base

configMapGenerator:
  - name: pass-api-config
    behavior: merge
    literals:
      - DD_ENVIRONMENT=dev
      - DD_VERSION=e8e04fb

  - name: pass-summary-api-config
    behavior: merge
    literals:
      - DD_ENVIRONMENT=dev
      - DD_VERSION=e8e04fb

images:
  - name: ghcr.io/datadog/sdlc-gitops-sample-stack/pass-api
    newTag: "e8e04fb"

  - name: ghcr.io/datadog/sdlc-gitops-sample-stack/pass-summary-api
    newTag: "e8e04fb"
