resources:
  - ../../base

configMapGenerator:
  - name: pass-api-config
    behavior: merge
    literals:
      - DD_ENVIRONMENT=dev
      - DD_VERSION=latest

  - name: pass-summary-api-config
    behavior: merge
    literals:
      - DD_ENVIRONMENT=dev
      - DD_VERSION=latest

images:
  - name: ghcr.io/DataDog/sdlc-gitops-sample-stack/pass-api
    newTag: "latest"

  - name: ghcr.io/DataDog/sdlc-gitops-sample-stack/pass-summary-api
    newTag: "latest"
