resources:
  - ../../base

configMapGenerator:
  - name: pass-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=635bb99875249a60a355937cc236169a0ce63666

  - name: pass-summary-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=635bb99875249a60a355937cc236169a0ce63666

  - name: pass-image-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=635bb99875249a60a355937cc236169a0ce63666

  - name: load-test-service-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=635bb99875249a60a355937cc236169a0ce63666

images:
  - name: ghcr.io/datadog/sdlc-gitops-sample-stack/pass-api
    newTag: "635bb99875249a60a355937cc236169a0ce63666"

  - name: ghcr.io/datadog/sdlc-gitops-sample-stack/pass-summary-api
    newTag: "635bb99875249a60a355937cc236169a0ce63666"

  - name: ghcr.io/datadog/sdlc-gitops-sample-stack/pass-image-api
    newTag: "635bb99875249a60a355937cc236169a0ce63666"

  - name: ghcr.io/datadog/sdlc-gitops-sample-stack/load-test-service
    newTag: "635bb99875249a60a355937cc236169a0ce63666"
