#cloud-config

write_files:
  - path: /etc/netplan/10-custom.yaml
    content: |
      network:
        version: 2
        ethernets:
          extra0:
            dhcp4: no
            match:
              macaddress: "{{WORKER_MAC}}"
            addresses: [{{WORKER_IP}}/24]

  - path: /tmp/bootstrap.sh
    permissions: 0777
    content: |
      #!/bin/bash
      netplan apply
      curl -sfL https://get.k3s.io > k3s 
      chmod +x k3s
      ./{{JOIN_COMMAND}}
