#cloud-config
write_files:
  - path: /etc/systemd/system/k3s.service.d/10-master.conf
    content: |
      [Service]
      Environment="K3S_KUBECONFIG_MODE=644"
      Environment="K3S_NODE_NAME=master"
      Environment="K3S_ROLE=master"
  - path: /etc/netplan/10-custom.yaml
    content: |
      network:
        version: 2
        ethernets:
          extra0:
            dhcp4: no
            match:
              macaddress: "52:54:00:4b:ab:cd"
            addresses: [192.168.64.100/24]
  - path: /tmp/bootstrap.sh
    permissions: 0777
    content: |
      #!/bin/bash
      export MASTER_IP=192.168.64.100
      netplan apply
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=$MASTER_IP" sh -
      mkdir -p /etc/rancher/k3s
      export K3S_TOKEN=$(cat /var/lib/rancher/k3s/server/node-token)
      echo "k3s agent --server https://$MASTER_IP:6443 --token $K3S_TOKEN" > /etc/rancher/k3s/join-command.txt

final_message: "k3s master node setup completed. Join command saved to /etc/rancher/k3s/join-command.txt"


