apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dd-sdlc-demo
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.cd-visibility-trigger.cd-visibility-webhook: ""
    dd_env: dev
    dd_service: simple-api
spec:
  destination:
    namespace: sdlc-demo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/overlays/dev
    repoURL: https://github.com/scottgerring/dd-sdlc-demo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
