apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sdlc-gitops-sample-stack
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.cd-visibility-trigger.cd-visibility-webhook: ""
    dd_env: dev
    dd_multiservice: true
    dd_k8s_cluster: sdlc-gitops-sample-cluster
spec:
  destination:
    namespace: sdlc-gitops-sample-stack
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/overlays/dev
    repoURL: https://github.com/DataDog/sdlc-gitops-sample-stack.git
    targetRevision: deploy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
