apiVersion: batch/v1
kind: Job
metadata:
  name: argo-postsync-job
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: sleep
          image: alpine:latest
          command: ["sleep", "0"]
      restartPolicy: Never
  backoffLimit: 0
