apiVersion: v1
kind: Service
metadata:
  name: pass-summary-api  
  labels:
    tags.datadoghq.com/service: "pass-summary-api"

spec:
  selector:
    app: pass-summary-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP