apiVersion: v1
kind: Service
metadata:
  name: pass-api
  labels:
    tags.datadoghq.com/service: "pass-api"


spec:
  selector:
    app: pass-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP