name: Setup after fork

on:
  workflow_dispatch:

jobs:
  replace-and-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      PREVIOUS_ORGNAME: 'datadog'  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replace previous orgname with target orgname
        run: |
          export REPO_OWNER=${{github.repository_owner}}
          export REPO_OWNER_LC=`echo "$REPO_OWNER" | awk '{print tolower($0)}'`
          find argocd-manifests manifests -name "*.yaml" -type f -exec sed -i "s/ghcr.io\/${{ env.PREVIOUS_ORGNAME }}/ghcr.io\/${REPO_OWNER_LC}/g" {} +
          find argocd-manifests manifests -name "*.yaml" -type f -exec sed -i "s/github.com\/${{ env.PREVIOUS_ORGNAME }}/github.com\/${REPO_OWNER_LC}/g" {} +
          sed -i "s/github.com\/${{ env.PREVIOUS_ORGNAME }}/github.com\/${REPO_OWNER_LC}/g" service.datadog.yaml
          git status

      - name: Create new branch
        run: |
          git config --global user.name "noreply"
          git config --global user.email "noreply@localhost"
          git checkout -b update-after-fork
          git add .
          git commit -m "Replace ${{ env.PREVIOUS_ORGNAME }} with ${{ github.repository_owner }}"
          git push -u origin update-after-fork
